<?php

	if ( function_exists( 'acf_add_local_field_group' ) ):

		acf_add_local_field_group( array(
			'key'                   => 'group_5947e7a25e583',
			'title'                 => 'EW Slider',
			'fields'                => array(
				array(
					'key'               => 'field_597608495cb13',
					'label'             => 'Pilt',
					'name'              => '',
					'type'              => 'tab',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'placement'         => 'top',
					'endpoint'          => 0,
				),
				array(
					'key'               => 'field_5947e7ae7c6d2',
					'label'             => 'pilt',
					'name'              => 'pilt',
					'type'              => 'image',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'return_format'     => 'url',
					'preview_size'      => 'large',
					'library'           => 'all',
					'min_width'         => '',
					'min_height'        => '',
					'min_size'          => '',
					'max_width'         => '',
					'max_height'        => '',
					'max_size'          => '',
					'mime_types'        => '',
				),
				array(
					'key'               => 'field_596a333c0d30b',
					'label'             => 'Tekst pildil',
					'name'              => 'tekst_pildil',
					'type'              => 'wysiwyg',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'default_value'     => '',
					'tabs'              => 'all',
					'toolbar'           => 'basic',
					'media_upload'      => 1,
					'delay'             => 0,
				),
				array(
					'key'               => 'field_5a299d798e430',
					'label'             => 'Slaidi URL link',
					'name'              => 'slaidi_link',
					'type'              => 'text',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '50',
						'class' => '',
						'id'    => '',
					),
					'default_value'     => '',
					'placeholder'       => '',
					'prepend'           => '',
					'append'            => '',
					'maxlength'         => '',
				),
				array(
					'key'               => 'field_5a29a1ae467ab',
					'label'             => 'Sihtkoht',
					'name'              => 'sihtkoht',
					'type'              => 'select',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '50',
						'class' => '',
						'id'    => '',
					),
					'choices'           => array(
						'_self'   => 'Samas aknas',
						'_blank'  => 'Uues aknas',
						'_parent' => 'Ülemises aknas',
						'_top'    => 'Uues täisaknas',
					),
					'default_value'     => array(),
					'allow_null'        => 0,
					'multiple'          => 0,
					'ui'                => 0,
					'ajax'              => 0,
					'return_format'     => 'value',
					'placeholder'       => '',
				),
				array(
					'key'               => 'field_597604d05d19e',
					'label'             => 'Rohkem valikuid',
					'name'              => '',
					'type'              => 'tab',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'placement'         => 'top',
					'endpoint'          => 0,
				),
				array(
					'key'               => 'field_597605df5d19f',
					'label'             => 'Pildi joondus',
					'name'              => 'pildi_joondus',
					'type'              => 'select',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '15',
						'class' => '',
						'id'    => '',
					),
					'choices'           => array(
						'left top'      => 'üleval vasak',
						'right top'     => 'üleval parem',
						'left bottom'   => 'all vasakul',
						'right bottom'  => 'paremal all',
						'center center' => 'Keskel',
					),
					'default_value'     => array(
						0 => 'center center',
					),
					'allow_null'        => 0,
					'multiple'          => 0,
					'ui'                => 0,
					'ajax'              => 0,
					'return_format'     => 'value',
					'placeholder'       => '',
				),
				array(
					'key'               => 'field_597607466fecc',
					'label'             => 'Teksti joondus',
					'name'              => 'teksti_joondus',
					'type'              => 'select',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '15',
						'class' => '',
						'id'    => '',
					),
					'choices'           => array(
						'lefttop'      => 'üleval vasak',
						'righttop'     => 'üleval parem',
						'leftbottom'   => 'all vasakul',
						'rightbottom'  => 'paremal all',
						'centercenter' => 'Keskel',
						'centerleft'   => 'Keskel vasakul',
						'centerright'  => 'Keskel paremal',
					),
					'default_value'     => array(
						0 => 'centercenter',
					),
					'allow_null'        => 0,
					'multiple'          => 0,
					'ui'                => 0,
					'ajax'              => 0,
					'return_format'     => 'value',
					'placeholder'       => '',
				),
				array(
					'key'               => 'field_597608e3715f3',
					'label'             => 'Klass',
					'name'              => 'klass',
					'type'              => 'text',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '15',
						'class' => '',
						'id'    => '',
					),
					'default_value'     => '',
					'placeholder'       => '',
					'prepend'           => '',
					'append'            => '',
					'maxlength'         => '',
				),
				array(
					'key'               => 'field_597a45afe7ca1',
					'label'             => 'Läbipaistev kiht',
					'name'              => '',
					'type'              => 'message',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'message'           => '',
					'new_lines'         => 'wpautop',
					'esc_html'          => 0,
				),
				array(
					'key'               => 'field_597a42d969834',
					'label'             => 'Läbipaistev kiht',
					'name'              => 'labipaistev_kiht',
					'type'              => 'true_false',
					'instructions'      => 'Saab lisada erinavat tooni kihte, mis katavad pildi, aga mitte teksti.',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '20',
						'class' => '',
						'id'    => '',
					),
					'message'           => '',
					'default_value'     => 0,
					'ui'                => 1,
					'ui_on_text'        => 'Jah',
					'ui_off_text'       => 'Ei',
				),
				array(
					'key'               => 'field_597a438969835',
					'label'             => 'Läbipaistva kihi värv',
					'name'              => 'labipaistva_kihi_varv',
					'type'              => 'color_picker',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '20',
						'class' => '',
						'id'    => '',
					),
					'default_value'     => '#000000',
				),
				array(
					'key'               => 'field_597a43d369837',
					'label'             => 'Läbipaistvus',
					'name'              => 'labipaistvus',
					'type'              => 'number',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '10',
						'class' => '',
						'id'    => '',
					),
					'default_value'     => '0.4',
					'placeholder'       => '',
					'prepend'           => '',
					'append'            => '',
					'min'               => '0.05',
					'max'               => '0.95',
					'step'              => '0.05',
				),
			),
			'location'              => array(
				array(
					array(
						'param'    => 'post_type',
						'operator' => '==',
						'value'    => 'slaidid',
					),
				),
			),
			'menu_order'            => 0,
			'position'              => 'normal',
			'style'                 => 'default',
			'label_placement'       => 'top',
			'instruction_placement' => 'label',
			'hide_on_screen'        => array(
				0  => 'permalink',
				1  => 'the_content',
				2  => 'excerpt',
				3  => 'custom_fields',
				4  => 'discussion',
				5  => 'comments',
				6  => 'revisions',
				7  => 'slug',
				8  => 'author',
				9  => 'format',
				10 => 'page_attributes',
				11 => 'featured_image',
				12 => 'categories',
				13 => 'tags',
				14 => 'send-trackbacks',
			),
			'active'                => 1,
			'description'           => '',
		) );

		acf_add_local_field_group( array(
			'key'                   => 'group_597627a4a2621',
			'title'                 => 'Slaideri sätted',
			'fields'                => array(
				array(
					'key'               => 'field_597627ae4efca',
					'label'             => 'Slaidi vahetamise kiirus',
					'name'              => 'slaidi_vahetamise_kiirus',
					'type'              => 'number',
					'instructions'      => 'Millisekundites nt 8000',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '25',
						'class' => '',
						'id'    => '',
					),
					'default_value'     => 8000,
					'placeholder'       => '',
					'prepend'           => '',
					'append'            => '',
					'min'               => '',
					'max'               => '',
					'step'              => 1000,
				),
				array(
					'key'               => 'field_597627e4845aa',
					'label'             => 'Luba slaidivahetuse nupud',
					'name'              => 'luba_slaidivahetus_nupud',
					'type'              => 'true_false',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '25',
						'class' => '',
						'id'    => '',
					),
					'message'           => '',
					'default_value'     => 0,
					'ui'                => 1,
					'ui_on_text'        => 'Jah',
					'ui_off_text'       => 'Ei',
				),
				array(
					'key'               => 'field_59762860845ab',
					'label'             => 'Luba slaidivahetuse nooled',
					'name'              => 'luba_slaidivahetus_nooled',
					'type'              => 'true_false',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '25',
						'class' => '',
						'id'    => '',
					),
					'message'           => '',
					'default_value'     => 0,
					'ui'                => 1,
					'ui_on_text'        => 'Jah',
					'ui_off_text'       => 'Ei',
				),
				array(
					'key'               => 'field_597628a6845ac',
					'label'             => 'Slaideri kõrgus',
					'name'              => 'slaideri_korgus',
					'type'              => 'number',
					'instructions'      => 'Protsentides',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '25',
						'class' => '',
						'id'    => '',
					),
					'default_value'     => 30,
					'placeholder'       => '',
					'prepend'           => '',
					'append'            => '',
					'min'               => '',
					'max'               => '',
					'step'              => '',
				),
				array(
					'key'               => 'field_597a4ea77f8ce',
					'label'             => 'Teksti ala laius',
					'name'              => 'teksti_ala_laius',
					'type'              => 'number',
					'instructions'      => 'Ala, mis ümbritseb nagu "wrapper" teksti paremat ja vasakut äärt pikslites',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '20',
						'class' => '',
						'id'    => '',
					),
					'default_value'     => '',
					'placeholder'       => '',
					'prepend'           => '',
					'append'            => '',
					'min'               => '',
					'max'               => '',
					'step'              => '',
				),
				array(
					'key'               => 'field_5ba3a2b77b0f1',
					'label'             => 'Taustapilt',
					'name'              => 'taustapilt',
					'type'              => 'image',
					'instructions'      => 'Kui panna taustapilt, siis ei pea slaididel taustapilte panema. Slaidina esitatakse ainult teksti väljale lisatud materjali.',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'return_format'     => 'url',
					'preview_size'      => 'thumbnail',
					'library'           => 'all',
					'min_width'         => '',
					'min_height'        => '',
					'min_size'          => '',
					'max_width'         => '',
					'max_height'        => '',
					'max_size'          => '',
					'mime_types'        => '',
				),
				array(
					'key'               => 'field_5ba891d90b59d',
					'label'             => 'Läbipaistev kiht',
					'name'              => '',
					'type'              => 'message',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'message'           => '',
					'new_lines'         => 'wpautop',
					'esc_html'          => 0,
				),
				array(
					'key'               => 'field_5ba892020b59e',
					'label'             => 'Läbipaistev kiht',
					'name'              => 'labipaistev_kiht',
					'type'              => 'true_false',
					'instructions'      => 'Saab lisada erinavat tooni kihte, mis katavad pildi, aga mitte teksti.',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '20',
						'class' => '',
						'id'    => '',
					),
					'message'           => '',
					'default_value'     => 0,
					'ui'                => 1,
					'ui_on_text'        => 'Jah',
					'ui_off_text'       => 'Ei',
				),
				array(
					'key'               => 'field_5ba892730b59f',
					'label'             => 'Läbipaistva kihi värv',
					'name'              => 'labipaistva_kihi_varv',
					'type'              => 'color_picker',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '20',
						'class' => '',
						'id'    => '',
					),
					'default_value'     => '#000000',
				),
				array(
					'key'               => 'field_5ba893ddcf3e0',
					'label'             => 'Läbipaistvus',
					'name'              => 'labipaistvus',
					'type'              => 'number',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '10',
						'class' => '',
						'id'    => '',
					),
					'default_value'     => '0.4',
					'placeholder'       => '',
					'prepend'           => '',
					'append'            => '',
					'min'               => '0.05',
					'max'               => '0.95',
					'step'              => '0.05',
				),
			),
			'location'              => array(
				array(
					array(
						'param'    => 'options_page',
						'operator' => '==',
						'value'    => 'acf-options-slaideri-satted',
					),
				),
			),
			'menu_order'            => 0,
			'position'              => 'normal',
			'style'                 => 'default',
			'label_placement'       => 'top',
			'instruction_placement' => 'label',
			'hide_on_screen'        => '',
			'active'                => 1,
			'description'           => '',
		) );

	endif;
?>